import random
import os
import csv
import logging
import numpy as np

try:
    import torch
    from torch_geometric.data import HeteroData
    HAS_PYG = True
except ImportError:
    HAS_PYG = False
    HeteroData = object  # dummy for type hints

logger = logging.getLogger("GNN-GraphBuilder")

SPECIES_METADATA = [
    {"id": 0, "name": "Indian Mackerel",  "scientific": "Rastrelliger kanagurta", "min_sst": 26.0, "max_sst": 29.0, "min_depth": 10,  "max_depth": 70,  "comm": 0.9,  "risk": 0.2},
    {"id": 1, "name": "Oil Sardine",      "scientific": "Sardinella longiceps",   "min_sst": 25.0, "max_sst": 28.5, "min_depth": 0,   "max_depth": 40,  "comm": 0.8,  "risk": 0.3},
    {"id": 2, "name": "Hilsa",            "scientific": "Tenualosa ilisha",       "min_sst": 24.0, "max_sst": 30.0, "min_depth": 0,   "max_depth": 50,  "comm": 0.95, "risk": 0.6},
    {"id": 3, "name": "Bombay Duck",      "scientific": "Harpadon nehereus",      "min_sst": 24.5, "max_sst": 28.0, "min_depth": 10,  "max_depth": 60,  "comm": 0.7,  "risk": 0.4},
    {"id": 4, "name": "Yellowfin Tuna",   "scientific": "Thunnus albacares",      "min_sst": 22.0, "max_sst": 28.0, "min_depth": 0,   "max_depth": 250, "comm": 1.0,  "risk": 0.7},
    {"id": 5, "name": "Penaeid Shrimp",   "scientific": "Penaeus indicus",        "min_sst": 26.0, "max_sst": 31.0, "min_depth": 2,   "max_depth": 30,  "comm": 0.85, "risk": 0.2},
]

# ID mapping: OBIS species_id string -> SPECIES_METADATA index
SPECIES_ID_MAP = {
    "mackerel":    0,
    "sardine":     1,
    "hilsa":       2,
    "bombay_duck": 3,
    "tuna":        4,
    "shrimp":      5,
}

REAL_CSV_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "data", "real_datasets", "indian_ocean_occurrences.csv"
)


def _load_real_csv() -> list:
    """
    Load the real OBIS+NOAA CSV generated by fetch_real_data.py.
    Returns list of row dicts. Returns empty list if file not found.
    """
    path = os.path.normpath(REAL_CSV_PATH)
    if not os.path.isfile(path):
        return []
    rows = []
    try:
        with open(path, "r", encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                rows.append(row)
        logger.info(f"✅ Loaded {len(rows)} real records from {path}")
    except Exception as e:
        logger.warning(f"⚠️ Could not read real CSV: {e}")
    return rows


def _build_real_graph_data(real_rows: list):
    """
    Build graph node features and occurrence edges from REAL OBIS+NOAA data.
    Each unique (lat, lon) coordinate cluster becomes an OceanGrid node.
    Species presence at each grid is backed by a real sighting record.
    """
    # Round coordinates to 0.5° grid cells to cluster nearby sightings
    grid_map = {}   # (lat_cell, lon_cell) -> aggregated features
    occurrence_edges = []  # (species_id, grid_id)

    for row in real_rows:
        try:
            lat = float(row["lat"])
            lon = float(row["lon"])
            sst = float(row["sst_celsius"])
            sal = float(row["salinity_psu"])
            chl = float(row["chlorophyll_mg_m3"])
            do  = float(row["dissolved_oxygen_mg_l"])
            dep = float(row["depth_m"])
            sp_key = row["species_id"]
        except (ValueError, KeyError):
            continue

        # Cluster to 0.5° grid cells (standard oceanographic resolution)
        lat_cell = round(round(lat / 0.5) * 0.5, 1)
        lon_cell = round(round(lon / 0.5) * 0.5, 1)
        cell_key = (lat_cell, lon_cell)

        if cell_key not in grid_map:
            grid_map[cell_key] = {
                "sst_vals": [], "sal_vals": [], "chl_vals": [],
                "do_vals": [], "dep_vals": [], "lat": lat_cell, "lon": lon_cell
            }
        grid_map[cell_key]["sst_vals"].append(sst)
        grid_map[cell_key]["sal_vals"].append(sal)
        grid_map[cell_key]["chl_vals"].append(chl)
        grid_map[cell_key]["do_vals"].append(do)
        grid_map[cell_key]["dep_vals"].append(dep)

        sp_id = SPECIES_ID_MAP.get(sp_key)
        if sp_id is not None:
            occurrence_edges.append((sp_id, cell_key))

    # Convert grid map to ordered list of feature vectors
    cell_keys = sorted(grid_map.keys())
    cell_index = {k: i for i, k in enumerate(cell_keys)}
    grid_features = []

    for k in cell_keys:
        g = grid_map[k]
        avg = lambda vals: round(sum(vals) / len(vals), 3) if vals else 0.0
        grid_features.append([
            avg(g["sst_vals"]),
            avg(g["sal_vals"]),
            avg(g["chl_vals"]),
            avg(g["do_vals"]),
            avg(g["dep_vals"]),
            g["lat"],
            g["lon"],
        ])

    # Deduplicate and resolve occurrence edges using cell_index
    sp_grid_src, sp_grid_dst = [], []
    seen = set()
    for sp_id, cell_key in occurrence_edges:
        g_id = cell_index.get(cell_key)
        if g_id is not None and (sp_id, g_id) not in seen:
            sp_grid_src.append(sp_id)
            sp_grid_dst.append(g_id)
            seen.add((sp_id, g_id))

    logger.info(f"✅ Real graph: {len(grid_features)} grid nodes, {len(sp_grid_src)} species-occurrence edges")
    return grid_features, sp_grid_src, sp_grid_dst, len(cell_keys)


def _species_occurs_synthetic(sp, sst, depth):
    """Fallback rule for synthetic data when CSV not available."""
    sst_ok = sp["min_sst"] <= sst <= sp["max_sst"]
    depth_ok = sp["min_depth"] <= depth <= sp["max_depth"]
    if sst_ok and depth_ok:
        return random.random() < 0.85
    elif sst_ok or depth_ok:
        return random.random() < 0.25
    else:
        return random.random() < 0.05


def _build_grid_adjacency(grid_features, num_grids, k=6):
    """Grid <-> Grid spatial adjacency using k-NN on lat/lon."""
    from sklearn.neighbors import BallTree
    latlon_rad = np.radians([[gf[5], gf[6]] for gf in grid_features])
    tree = BallTree(latlon_rad, metric='haversine')
    _, neighbor_idx = tree.query(latlon_rad, k=min(k + 1, num_grids))
    src, dst = [], []
    for g1, neighbors in enumerate(neighbor_idx):
        for g2 in neighbors:
            g2 = int(g2)
            if g1 != g2:
                src.append(g1)
                dst.append(g2)
    return src, dst


SEASON_SHIFTS = {
    "pre_monsoon":  {"sst_offset": 1.5,  "chl_offset": -0.5},
    "monsoon":      {"sst_offset": -1.0, "chl_offset": 1.5},
    "post_monsoon": {"sst_offset": 0.0,  "chl_offset": 0.3},
}


def build_hetero_graph(num_grids=200, num_edna=150, seed=None, season="post_monsoon"):
    """
    Build heterogeneous knowledge graph for the GNN.
    Uses REAL data from OBIS+NOAA CSV if available.
    Falls back to physics-informed synthetic data if CSV not found.
    """
    if seed is not None:
        random.seed(seed)

    num_species = len(SPECIES_METADATA)
    shift = SEASON_SHIFTS.get(season, SEASON_SHIFTS["post_monsoon"])

    # ── Attempt to load REAL data ──────────────────────────────────────────────
    real_rows = _load_real_csv()
    using_real_data = len(real_rows) > 50

    if using_real_data:
        logger.info("🌊 Building graph from REAL OBIS+NOAA dataset")
        grid_features, species_grid_src, species_grid_dst, num_grids = _build_real_graph_data(real_rows)
    else:
        # ── Fallback: physics-informed synthetic data ──────────────────────────
        logger.info("⚠️ Real CSV not found — using physics-informed synthetic data as fallback")
        grid_features = []
        for i in range(num_grids):
            lat = random.uniform(5.0, 25.0)
            lon = random.uniform(65.0, 95.0)
            sst = random.uniform(22.0, 31.0) + shift["sst_offset"]
            salinity = random.uniform(32.0, 36.0)
            chlorophyll = max(0.05, random.uniform(0.1, 5.0) + shift["chl_offset"])
            do = random.uniform(3.0, 7.0)
            depth = random.uniform(0.0, 300.0)
            grid_features.append([sst, salinity, chlorophyll, do, depth, lat, lon])

        species_grid_src, species_grid_dst = [], []
        for sp_id, sp in enumerate(SPECIES_METADATA):
            for g_id in range(num_grids):
                sst, _, _, _, depth, _, _ = grid_features[g_id]
                if _species_occurs_synthetic(sp, sst, depth):
                    species_grid_src.append(sp_id)
                    species_grid_dst.append(g_id)

    # ── Species node features (same regardless of data source) ────────────────
    species_features = [
        [sp["min_sst"], sp["max_sst"], sp["min_depth"], sp["max_depth"], sp["comm"], sp["risk"]]
        for sp in SPECIES_METADATA
    ]

    # ── eDNA nodes ─────────────────────────────────────────────────────────────
    edna_features = [
        [random.uniform(0.5, 1.0), random.choice([0, 1, 2])]
        for _ in range(num_edna)
    ]

    # ── eDNA -> Grid edges ─────────────────────────────────────────────────────
    actual_num_grids = len(grid_features)
    edna_grid_src = [e_id for e_id in range(num_edna)]
    edna_grid_dst = [random.randint(0, actual_num_grids - 1) for _ in range(num_edna)]

    # ── eDNA -> Species edges (biased to real occurrences) ────────────────────
    occurs_by_grid = {}
    for sp_id, g_id in zip(species_grid_src, species_grid_dst):
        occurs_by_grid.setdefault(g_id, []).append(sp_id)

    edna_species_src, edna_species_dst = [], []
    for e_id in range(num_edna):
        g_id = edna_grid_dst[e_id]
        candidates = occurs_by_grid.get(g_id, [])
        if candidates and random.random() < 0.8:
            sp_id = random.choice(candidates)
        else:
            sp_id = random.randint(0, num_species - 1)
        edna_species_src.append(e_id)
        edna_species_dst.append(sp_id)

    # ── Grid <-> Grid spatial adjacency ───────────────────────────────────────
    grid_grid_src, grid_grid_dst = _build_grid_adjacency(grid_features, actual_num_grids)

    # ── Assemble graph ─────────────────────────────────────────────────────────
    if HAS_PYG:
        data = HeteroData()
        data['OceanGrid'].x   = torch.tensor(grid_features,    dtype=torch.float)
        data['Species'].x     = torch.tensor(species_features, dtype=torch.float)
        data['eDNAMarker'].x  = torch.tensor(edna_features,    dtype=torch.float)
        data['Species', 'species_occurs_in_grid',   'OceanGrid'].edge_index = torch.tensor([species_grid_src, species_grid_dst], dtype=torch.long)
        data['eDNAMarker', 'edna_detected_in_grid', 'OceanGrid'].edge_index = torch.tensor([edna_grid_src,    edna_grid_dst],    dtype=torch.long)
        data['eDNAMarker', 'edna_identifies_species','Species'].edge_index  = torch.tensor([edna_species_src, edna_species_dst], dtype=torch.long)
        data['OceanGrid', 'grid_correlates_with_grid','OceanGrid'].edge_index = torch.tensor([grid_grid_src,  grid_grid_dst],    dtype=torch.long)
        data.using_real_data = using_real_data
        return data
    else:
        return {
            "nodes": {
                "OceanGrid":  grid_features,
                "Species":    species_features,
                "eDNAMarker": edna_features,
            },
            "edges": {
                "species_occurs_in_grid":      (species_grid_src, species_grid_dst),
                "edna_detected_in_grid":       (edna_grid_src,    edna_grid_dst),
                "edna_identifies_species":     (edna_species_src, edna_species_dst),
                "grid_correlates_with_grid":   (grid_grid_src,    grid_grid_dst),
            },
            "using_real_data": using_real_data,
        }


def sample_negative_edges(pos_src, pos_dst, num_src_nodes, num_dst_nodes, num_neg=None, seed=None):
    """Generate negative (non-occurrence) species-grid edges for link prediction training."""
    if seed is not None:
        random.seed(seed)
    pos_set = set(zip(pos_src, pos_dst))
    if num_neg is None:
        num_neg = len(pos_src)
    neg_src, neg_dst = [], []
    attempts = 0
    max_attempts = num_neg * 50
    while len(neg_src) < num_neg and attempts < max_attempts:
        s = random.randint(0, num_src_nodes - 1)
        d = random.randint(0, num_dst_nodes - 1)
        attempts += 1
        if (s, d) not in pos_set:
            neg_src.append(s)
            neg_dst.append(d)
            pos_set.add((s, d))
    return neg_src, neg_dst


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    graph = build_hetero_graph(seed=42)
    print("Graph built successfully.")
    if HAS_PYG:
        print(graph)
        print("Using real data:", graph.using_real_data)
    else:
        print("Using dict fallback. Real data:", graph.get("using_real_data"))